[package]
name = "io-streams"
version = "0.2.3-alpha.0"
description = "Unbuffered and unlocked I/O streams"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["io"]
categories = ["rust-patterns"]
repository = "https://github.com/sunfishcode/io-streams"
readme = "README.md"

[build-dependencies]
rustc_version = "0.3.0"

[dependencies]
char-device = { version = "0.2.0", optional = true }
duplex = "0.2.0"
layered-io = { version = "0.3.1", optional = true }
memchr = "2.3.4"
parking = "2.0.0"
socketpair = { version = "0.5.0", optional = true }
system-interface = { version = "0.6.2", features = ["os_pipe"] }
terminal-io = { version = "0.2.1", optional = true }
unsafe-io = { version = "0.5.2", features = ["os_pipe"] }
utf8-io = { version = "0.3.1", optional = true }

# WASI doesn't support pipes yet
[target.'cfg(not(target_os = "wasi"))'.dependencies]
os_pipe = "0.9.2"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2.81"

[dev-dependencies]
anyhow = "1.0.38"
cap-tempfile = "0.13.6"
char-device = "0.2.0"
duplex = { version = "0.2.0", features = ["char-device"] }

[features]
default = []
use-socketpair = ["socketpair", "duplex/socketpair", "system-interface/socketpair"]
use-char-device = ["char-device", "duplex/char-device", "system-interface/char-device"]

[badges]
maintenance = { status = "actively-developed" }
