[package]
name = "io-streams"
version = "0.0.0"
description = "Unbuffered and unlocked I/O streams"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["io"]
categories = ["rust-patterns"]
repository = "https://github.com/sunfishcode/io-streams"
readme = "README.md"

[build-dependencies]
rustc_version = "0.3.0"

[dependencies]
char-device = { version = "0.0.0", optional = true }
duplex = { git = "https://github.com/sunfishcode/duplex", branch = "main" }
io-ext = { git = "https://github.com/sunfishcode/io-ext", branch = "main", optional = true }
memchr = "2.3.4"
once_cell = "1.3.1"
parking = "2.0.0"
socketpair = { version = "0.3.1", optional = true }
system-interface = { version = "0.5.4", features = ["os_pipe"] }
terminal-support = { git = "https://github.com/sunfishcode/terminal-support", branch = "main", optional = true }
unsafe-io = { version = "0.3.0", features = ["os_pipe"] }

# WASI doesn't support pipes yet
[target.'cfg(not(target_os = "wasi"))'.dependencies]
os_pipe = "0.9.2"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2.81"

[dev-dependencies]
anyhow = "1.0.38"
cap-tempfile = "0.11.0"
char-device = "0.0.0"
system-interface = { version = "0.5.3", features = ["char-device"] }
duplex = { git = "https://github.com/sunfishcode/duplex", branch = "main", features = ["char-device"] }

[features]
default = []
use-socketpair = ["socketpair", "duplex/socketpair", "system-interface/socketpair"]
use-char-device = ["char-device", "duplex/char-device", "system-interface/char-device"]

[badges]
maintenance = { status = "actively-developed" }
